### ISSUE TITLE
cmake/make build problems

### ISSUE THREAD

**Issue by informer2016** [himanshugoel2797/Cardinal-semicolon#2]
Out of curiosity _(to see if Cardinal; could fit on a virtual floppy for coreboot open-source BIOS, see #1 )_ I tried building the latest Cardinal; image from the source. First I got "Did not find file Compiler/-ASM" warning:
```
~/Cardinal-semicolon/build$ CC=clang cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_SYSTEM_NAME="Generic" -D_CMAKE_TOOLCHAIN_PREFIX=llvm- ..
-- The ASM compiler identification is unknown
-- Found assembler: /usr/bin/clang
-- Warning: Did not find file Compiler/-ASM
-- Configuring done
-- Generating done
-- Build files have been written to: ~/Cardinal-semicolon/build
```
Then, while building it further with make, I get this error:
```
~/Cardinal-semicolon/build$ make
[  1%] Linking C static library libc.a
Error running link command: No such file or directory
common/CMakeFiles/c.dir/build.make:198: recipe for target 'common/libc.a' failed
make[2]: *** [common/libc.a] Error 2
CMakeFiles/Makefile2:182: recipe for target 'common/CMakeFiles/c.dir/all' failed
make[1]: *** [common/CMakeFiles/c.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
Any ideas how I could fix it?

**Comment by himanshugoel2797** [comment]
Sorry, this flew under my radar. It's been 3.5 years so I guess you probably aren't still waiting, closing but open to reopening :)

Also it's unlikely this will fit well on a floppy. The 'kernel' itself is tiny since it doesn't do anything other than load modules and manage symbol names, but all the modules on the initrd add a lot of extra data.
